### ISSUE TITLE
search field

### ISSUE THREAD

**Issue by lauraturk** [cbandrow/ideabox#8]
Take a look at the search field start. The :content() Selector won't work cause it only accepts a string and we'll run into issues w/ it having to be case sensitive. Filter? Map? What do you think?

**Comment by cbandrow-zz** [comment]
I think we can use map for it, as filter would look for truthy values and just append the data back. Lets look into it more and see what we can do.

**Comment by lauraturk** [comment]
I guess I was thinking we'd do some kind of addClass to hide the elements that don't match rather than append or remove.

**Comment by cbandrow-zz** [comment]
Knocking it out of the park here, Laura! Great work brainstorming a solution to search data.
